version: "3.8"

services:
  elastic:
    image: elasticsearch:8.0.0
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - elastic-data:/usr/share/elasticsearch/data


volumes:
  elastic-data:
    driver: local